### ISSUE TITLE
Add loguru using possibility

### ISSUE THREAD

**Issue by newpotsdev** [prostomarkeloff/vk.py#10]
Add loguru (https://github.com/Delgan/loguru) using possibility in vk.py! Don`t add it to requirements.txt, just check:
```python
try:
 from loguru import logger
except ModuleNotFoundError:
 import logging # ...
```

**Comment by prostomarkeloff** [comment]
ok, you may create pull request with this feature

**Comment by newpotsdev** [comment]
ты че курва ахуел схуяли

**Comment by sumalaev** [comment]
ты че ахуел выебыватся я тебе щас пизды дам мразота тупая

**Comment by Inzilkin** [comment]
FIX LIB, HELLO MAN, YOU LP HAVE PROBLEMS!!!

**Comment by sumalaev** [comment]
используйте этот комментарий как дизлайк

**Comment by 0susboy0** [comment]
СЛУШАЙ СЮДА, ЕБЛО ОСЛИНОЕ, Я РОМОЧКУ ЛЮБЛЮ, ТАК ЧТО ТЫ **БЕГИ**

**Comment by sumalaev** [comment]
ПОШЕЛ НАХУЙ ХУЕПУТАЛО

**Comment by sumalaev** [comment]
давайте засрем этому пидарасу иссу гавноссу

**Comment by 0susboy0** [comment]
ясно соси лох

**Comment by sumalaev** [comment]
сам соси хуесос

**Comment by 0susboy0** [comment]
соси соси сладкий

**Comment by 0susboy0** [comment]
### ясно отсосал спс брат

**Comment by kesha1225** [comment]
А зачем конфа го тут общаться

**Comment by sumalaev** [comment]
### арсений пидарас

**Comment by 0susboy0** [comment]
АХХАХАХАХАХХ согласен кстати
