### ISSUE TITLE
Удали VKBottle

### ISSUE THREAD

**Issue by 0susboy0** [prostomarkeloff/vk.py#12]
вк боттле умер, над ним больше не работают..

**Comment by sumalaev** [comment]
та и ваще асрений пидарас хахахахаахахахаха

**Comment by prostomarkeloff** [comment]
Последний коммит - ~6 минут назад. [тык](https://github.com/timoniq/vkbottle/commit/3256ccf7404c215e55577e508ef446bd58a5f2fb)

**Comment by timoniq** [comment]
ору что это

**Comment by 0susboy0** [comment]
чо ты орешь, чучело

**Comment by timoniq** [comment]
> чо ты орешь, чучело

всм вопрос что это где доказательства

**Comment by 0susboy0** [comment]
сам себе ставит сердечко, **чучело ясно**

**Comment by timoniq** [comment]
> сам себе ставит сердечко, **чучело ясно**

метод самоутверждения
вопрос что это как дела привет
