### ISSUE TITLE
`post_process_event` in Middleware will accept `result` argument

### ISSUE THREAD

**Issue by prostomarkeloff** [prostomarkeloff/vk.py#20]
Метод `post_process_event` будет принимать аргумент `result`, который является результатом работы обработчика. Если обработчик не будет вызван, то этот метод не будет вызван.

**Comment by prostomarkeloff** [comment]
Событие будет приходить не в виде словаря event, а в виде полноценного объекта с полями:
`group_id`, `type`, `object`.

**Comment by prostomarkeloff** [comment]
Готово.

**Comment by prostomarkeloff** [comment]
Нужно обновить документацию.

**Comment by crinny** [comment]
какой же бомбер охуенный
