### ISSUE TITLE
VBML as standart rule for text parsing

### ISSUE THREAD

**Issue by prostomarkeloff** [prostomarkeloff/vk.py#26]
Так как vbml уже доступен в PyPI появится новое правило для обработчиков сообщений `vbml`, которое будет использовать VBML.

**Comment by prostomarkeloff** [comment]
090d63bb73dce0b86ec00ea8a150035b296dab0d

**Comment by timoniq** [comment]
ура вбмл кто же автор который его сделал скажите такой хороший проект

**Comment by prostomarkeloff** [comment]
Нужно обновить документацию.

**Comment by timoniq** [comment]
Нужно похвалить автора

**Comment by newpotsdev** [comment]
Make an example of VBML using please

**Comment by timoniq** [comment]
People still wait for code instances

**Comment by prostomarkeloff** [comment]
> People still wait for code instances

No idea.
