### ISSUE TITLE
Правила которые будут включены во все обработчики

### ISSUE THREAD

**Issue by prostomarkeloff** [prostomarkeloff/vk.py#27]
У именнованых правил (`NamedRules`) появятся 2 новых поля (`required` и `default`). Если `required` равно `True`, то данное правило будет включено во все обработчики, со стандартным значением `default`, которое изначально равно `None`.

**Comment by prostomarkeloff** [comment]
57890e7ee89f4525f8a0e20fed665a9bf1a045d0

**Comment by prostomarkeloff** [comment]
Нужно обновить документацию.

**Comment by Waika28** [comment]
Жду документацию...
