### ISSUE TITLE
Возможность писать execute-запросы на Python (Python -> VKScript)

### ISSUE THREAD

**Issue by yilbegan** [prostomarkeloff/vk.py#28]
Добавить возможность ограниченной конвертации python-кода в VK Script для упрощения написания execute запросов.

- [x]  Конвертирование **Python** -> **VK Script**
- [x]  Тесты
- [ ]  Ограниченная поддержка **for**-блоков
- [ ]  Документация и докстринги
- [ ]  Пре-/Пост-обработка 
- [ ]  Примеры использования
- [ ]  Кеширование 
- [ ]  Поддержка **with**

**Comment by prostomarkeloff** [comment]
Использовать `pydantic.BaseModel` вместо `dataclasses`. https://github.com/prostomarkeloff/vk.py/blob/dev/vk/utils/vkscript/converter.py#L7

**Comment by python273** [comment]
Интересная фича, я тоже вот баловался с конвертацией https://github.com/python273/vk_api_vkscript#vk_api_vkscript

Как я понял оно сейчас текст python конвертит в VKScript, но в идеале иметь валидный python код. Тогда например можно будет python функцию тестировать, но запускать потом через execute

Вот тут например:
https://github.com/prostomarkeloff/vk.py/blob/1c1237561e9e884bc5ff2886c3a30917030c47c1/tests/test_execute.py#L49-L54
если запускать в python, то упадет:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in demo_functions
AttributeError: 'list' object has no attribute 'shift'
```
